### ISSUE TITLE
Set up two more validators for testnet

### ISSUE THREAD

**Issue by troggy** [leapdao/meta#166] opened 2019-10-29 12:17 UTC
# Bounty

Testnet currently has 2 validators:
- one operated by @troggy (let's call it "The Grandpa")
- another one operated by @eshavkun

For resilient setup the network needs at least 4 validators — the lowest amount to afford one validator to be offline and still has 2/3 quorum for block proposals.

## Scope
- set up two more leap-nodes in a secure fashion (access to the machine should be restricted)
- update the published network config
- make sure epoch length is 4 for the network
- assign new validators to the PoaOperator contract slots

## Deliverables
- updated network config
- announcement on Slack

## Publicly visible delivery
- tweet or blog post

## Gain for the project
resilient testnet. Ability to check bigger validator set setup before applying on mainnet

## Roles
bounty gardener: @troggy / 50 DAI flat
bounty worker: name / 85%
bounty reviewer: name / 15%

## Funded by

Ops Circle

**Comment by johannbarbie** [comment] 2019-11-23 10:25
duplicate of https://github.com/leapdao/meta/issues/178

**Closed** 2019-11-27 12:46 UTC
Labels: bounty, operations, size-S
